Feat/20240425 green it introduction 1
zatsit-oss/zats-blog-content pull request #20
Opened 2024-06-28 11:52 UTC by emmanuelperu

2024-06-28 12:36 UTC, M3lkior requested changes

2024-06-28 12:36 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/evolution-cobalt.png
a convertir en webp :)

2024-06-28 12:36 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/evolution-production-metaux.png
a convertir en webp :)

2024-06-28 12:36 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/exemple-cuivre.png
a convertir en webp :)

2024-06-28 12:36 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/palabora-Afrique-Sud_Dillon-Marsh.jpg
a convertir en webp :)

2024-06-28 12:36 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/roue-metaux.jpeg
a convertir en webp :)

2024-06-28 12:36 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/smartphone-composition.png
a convertir en webp :)

2024-06-28 12:36 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/smartphone-composition.png
a convertir en webp :)

2024-06-28 12:36 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/index.md
> +title: "Le greenIT episode 1 : Au fond du trou ?"
```suggestion
title: "Le Green IT, épisode 1 : Au fond du trou ?"
```

2024-06-28 12:36 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/index.md
> +Le printemps 2024 est erminé (si vous l'avez vu passé) et nous voyons clairement que nous commençons à manquer de prénoms pour les tempêtes,
```suggestion
Le printemps 2024 est terminé (si vous l'avez vu passé) et nous voyons clairement que nous commençons à manquer de prénoms pour les tempêtes,
```

2024-06-28 12:36 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/index.md
> +Entre les deux, il y a bien sûr la consommation énergétique liée à l'extraction, la fabrication, la distribution et l'utilisation.
```suggestion

L'empreinte de l'industrialisation est avérée dans l'augmentation, des gaz à effet de serre, mais l'empreinte liée aux matières 
premières nécessaires à cette industrialisation et à ses produits finis l'est moins.
Entre les deux, il y a bien sûr la consommation énergétique liée à l'extraction, la fabrication, la distribution et l'utilisation.
```

2024-06-28 12:36 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/index.md
> +- La conférence d'Aurore Stéphant aux APIdays (même si j'avais déjà vu certaines de ces interventions sur Youtube et notamment ses deux passages chez Thinkerview).
linker son profil Linked In ainsi que ses vidéos Thinkerview ?

2024-06-28 12:36 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/index.md
> +- Un Meetup Techrocks en début d'année sur le sujet qui nous occupe.
```suggestion
- Un Meetup [Techrocks](https://www.tech.rocks/) en début d'année sur le sujet qui nous occupe.
```

2024-06-28 12:36 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/index.md
> +À travers les différentes époques la demande en métaux n'a jamais cessé de croître, il y a pu avoir des ralentissements dûs à des évènements gépolotiques ou sanitaires (guerres, épidémies...), mais l
```suggestion
À travers les différentes époques, la demande en métaux n'a jamais cessé de croître : il y a pu avoir des ralentissements dûs à des évènements gépolotiques ou sanitaires (guerres, épidémies...), mais la demande est toujours croissante.
```

2024-06-28 12:36 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/index.md
> +Et oui, avec des composants comme l'Arsenic et l'Antimoine, certes en quantité minime et stabilisé dans votre smartphone, mais qu'en est-il de leur exploitation...
```suggestion
Et oui, avec des composants comme l'Arsenic et l'Antimoine, certes en quantité minime et stabilisé dans votre smartphone, mais qu'en est-il de leur exploitation ?
```

2024-06-28 12:36 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/index.md
> +Le problème c'est que les métaux sont inégalement présents dans les sols et quand on trouve plus facilement du fer et de l'aluminium, il faudra dans le meilleur des cas extraire 1 tonne pour obtenir
```suggestion
Le problème c'est que les métaux sont inégalement présents dans les sols et quand on trouve plus facilement du fer et de l'aluminium, il faudra dans le meilleur des cas extraire 1 tonne de minerais pour obtenir 1g d'or.
```

2024-06-28 12:36 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/index.md
> +Il existe donc des mines qui sont spécialisées dans l'extraction d'un ou plusieurs éléments, mais là ou on va trouver un métal plus abondfmment par exemple, on va aussi en trouver plein d'autres.
```suggestion
Il existe donc des mines qui sont spécialisées dans l'extraction d'un ou plusieurs éléments, mais là où on va trouver un métal plus abondamment par exemple, on va aussi en trouver plein d'autres.
```

2024-06-28 12:36 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/index.md
> +Cette infographie nous explique que pour chaque élément au centre trouvé, on a de fortes chances de trouver les autres. Plus les autres éléments sont proches du centre, plus ils ont de chances d'être
```suggestion
Cette infographie nous explique que pour chaque élément trouvé (au centre), on a de fortes chances de trouver les autres. 
* Plus les autres éléments sont proches du centre, plus ils ont de chance d'être récupéré comme **co-produit**
* Plus ils sont proches de l'extérieur et plus ils ont de risques d'être rejetés dans les **déchets miniers**
```

2024-06-28 12:36 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/index.md
> +Pour extraire des métaux de la roche, il y a des procédés mécaniques, thermiques, chimiques pour par exemple partir de la roche et obtenir des catodes de cuivres. Tout celà avec une consommation d'ea
```suggestion
Pour extraire des métaux de la roche, il y a des procédés mécaniques, thermiques et chimiques pour, par exemple, partir de la roche et obtenir des catodes de cuivres. Tout celà avec une consommation d'eau et d'énergie phénoménale.
```

2024-06-28 12:36 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/index.md
> +Ci-dessous, on peut se rendre compte, avec la représentation de la tour Eiffel, de la taille d'un site (extraction + exploitation + emprise en surface des déchets) pour la "mine de cuivre" de Palabor
```suggestion
Ci-dessous, on peut se rendre compte, avec la représentation de la tour Eiffel, de la taille d'un site (extraction + exploitation + emprise en surface des déchets) pour la **mine de cuivre** de Palabora
```

2024-06-28 12:36 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/index.md
> +Située en Afrique du Sud, cette mine a été exploitée pendant presque 40 ans [plus de détail sur cette mine avec ce lien](https://planet-terre.ens-lyon.fr/ressource/Img784-2023-06-05.xml).
```suggestion
Située en Afrique du Sud, cette mine a été exploitée pendant presque 40 ans. ([plus de détail sur cette mine avec ce lien](https://planet-terre.ens-lyon.fr/ressource/Img784-2023-06-05.xml)).
```

2024-06-28 12:36 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/index.md
> +D'autres exemples de mines gigantesques existent (cette fois c'est du charbon, mais ça symbolise bien l'extraction minière), plus proche de nous, comme la [mine de Hambach en Allemagne](https://fr.wi
```suggestion

D'autres exemples de mines gigantesques existent (cette fois c'est du charbon, mais ça symbolise bien l'extraction minière), plus proche de nous, comme la [mine de Hambach en Allemagne](https://fr.wikipedia.org/wiki/Mine_de_Hambach#).
```

2024-06-28 12:36 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/index.md
> +La conséquence principale de cette exploitation est bien entendu d'approvisionner toutes nos industries : transports, énergie, armement, agriculture... enfin tout ce qui nécessite aujourd'hui des mét
```suggestion
La conséquence principale de cette exploitation est bien entendu d'approvisionner toutes nos industries : transports, énergie, armement, agriculture... enfin tout ce qui nécessite aujourd'hui des métaux, c'est à dire à peu prés tout, dans sa composition, sa construction ou sa logistique. 

Faites l'exercice : "Quel artefact utilisez-vous dans votre quotidien qui n’est pas dépendant de l’industrie minière dans sa fabrication, sa vente, son transport ?"
```

2024-06-28 12:36 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/index.md
> +conséquences politiques et sociales, parler de fairphone et des mines de Cobalt...
pas compris ces deux phrases ..

2024-06-28 12:36 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/index.md
> +
```suggestion
Ne soyons pas pessimistes sur la capacité de l'Homme à trouver des solutions, mais nous passerons forcément à une diminution de l'usage des métaux. D'abord, parce que la teneur en métaux baisse dans les exploitations (même si on trouvera toujours de nouvelles mines) et ensuite parceque ça coutera toujours plus d'énergie, qui est elle aussi n'est pas inépuisable ?

```

2024-06-28 12:36 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/index.md
> +Alors à l'échelle du numérique, que pouvons-nous faire ? Se poser les bonnes questions sur les usages toujours plus gourmands en ressources, concevoir mieux pour utiliser plus longtemps.
je rajouterai un dernier paragraphe pour annoncer les prochains articles orientés eco conception it et autres non ?

2024-06-28 12:36 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/index.md
> +[![Partage Linkedin](../../../static/img/icon-x.webp)](https://twitter.com/intent/tweet?)
les slugs ne sont pas bon je pense

2024-06-28 14:14 UTC, emmanuelperu commented on blog/green/20240621-greenIT-introduction-1/index.md
> +[![Partage Linkedin](../../../static/img/icon-x.webp)](https://twitter.com/intent/tweet?)
effectivement il y a aussi une erreur sur les liens sur les autres articles, je ferai une autre PR pour ça

2024-06-28 14:55 UTC, M3lkior requested changes

2024-06-28 14:55 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/index.md
> +*Source https://www.systext.org/sites/all/animationreveal/mtxsmp/#/1*
```suggestion
*Source https://www.systext.org/sites/all/animationreveal/mtxsmp/#/1*
```
```suggestion
*Source : [Systext](https://www.systext.org/sites/all/animationreveal/mtxsmp/#/1) *
```

2024-06-28 14:55 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/index.md
> +*Source : https://www.systext.org/sites/default/files/RP_SystExt_Controverses-Mine_VOLET-1_Nov2021_maj.pdf*
```suggestion
*Source : [Systext](https://www.systext.org/sites/default/files/RP_SystExt_Controverses-Mine_VOLET-1_Nov2021_maj.pdf)*
```

2024-06-28 14:55 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/index.md
> +- [Reesources mnières en France](https://www.mineralinfo.fr/fr/ressources-minerales-france-gestion/mines-france)
```suggestion
- [Ressources minières en France](https://www.mineralinfo.fr/fr/ressources-minerales-france-gestion/mines-france)
```

2024-06-28 14:55 UTC, M3lkior commented on blog/green/20240621-greenIT-introduction-1/index.md
> +[![Partage X](../../../static/img/icon-x.webp)](https://twitter.com/intent/tweet?text=Quels%20sont%20les%20impacts%20de%20l%27exploitation%20mini%C3%A8re%20pour%20la%20production%20de%20nos%20apparei
slugs a changer non ?

2024-07-08 11:58 UTC, emmanuelperu commented on blog/green/20240621-greenIT-introduction-1/index.md
> +[![Partage X](../../../static/img/icon-x.webp)](https://twitter.com/intent/tweet?text=Quels%20sont%20les%20impacts%20de%20l%27exploitation%20mini%C3%A8re%20pour%20la%20production%20de%20nos%20apparei
je les ai changé.

2024-07-09 11:35 UTC, germainlefebvre4 commented on blog/green/20240621-greenIT-introduction-1/index.md
> +À travers les différentes époques, la demande en métaux n'a jamais cessé de croître : il y a pu avoir des ralentissements dûs à des évènements gépolotiques ou sanitaires (guerres, épidémies...), mais
`gépolotiques` > `gépolitiques`

2024-07-09 11:38 UTC, germainlefebvre4 commented on blog/green/20240621-greenIT-introduction-1/index.md
> +Vous avez peut-être déjà vu les [photographies de Dillon Marsh](https://dillonmarsh.com/fwiw.html) qui montre "à l'échelle" la taille des mines en elle même, leur emprise sur les espaces autour, en r
`elle même` > `elle-même`

2024-07-09 11:40 UTC, germainlefebvre4 commented on blog/green/20240621-greenIT-introduction-1/index.md
> +Des procès sont régulièrement intentés contre les exploitants, cependant ça ne permet pas de réparer les dommages occasionnés. au delà des accidents, la fin d'une exploitation d'un site minier ne sig
`au delà` > `Au-delà`

2024-07-09 11:41 UTC, germainlefebvre4 commented on blog/green/20240621-greenIT-introduction-1/index.md
> +L'extraction minière est aussi source de conflits politiques et sociales. Les ressources ne sont pas également réparties sur le globe et dans certains pays les conditions de travail des adultes et au
New line missing for yaml lint

2024-07-09 11:42 UTC, germainlefebvre4 commented on blog/green/20240621-greenIT-introduction-1/index.md
> +Se poser les bonnes questions sur les usages toujours plus gourmands en ressources : concevoir mieux pour utiliser plus longtemps ! Celà passe par une meilleure analyse des besoins, de faire des comp
`concevoir mieux` ou `mieux concevoir` ?

2024-07-09 11:43 UTC, germainlefebvre4 commented on blog/green/20240621-greenIT-introduction-1/index.md
> +[Tristant Nitot](https://www.youtube.com/watch?v=LzBv5H24OxY), lors du dernier DevFest Lille, nous expliquait clairement que l'amélioration de la puissance de calcul (illustrée par laLoi de Moore) a
`laLoi de Moore` > `la Loi de Moore`

2024-07-09 11:45 UTC, germainlefebvre4 commented on blog/green/20240621-greenIT-introduction-1/index.md
> +Soyez curieux à votre tour, chercher de l'information dans les sources citées (et d'autres) pour vous faire votre propre opinion et peut-être changer quelques habitudes.
`chercher` > `cherchez`

2024-07-09 11:45 UTC, germainlefebvre4 commented on blog/green/20240621-greenIT-introduction-1/index.md
> +- [USI 2022 "Ruée minière au XXIè siècle : jusqu'où les limites seront-elles repoussées ?"](https://www.youtube.com/watch?v=i8RMX8ODWQs)
New line missing for yaml lint

2024-08-02 09:00 UTC, emmanuelperu commented on blog/green/20240621-greenIT-introduction-1/index.md
> +Se poser les bonnes questions sur les usages toujours plus gourmands en ressources : concevoir mieux pour utiliser plus longtemps ! Celà passe par une meilleure analyse des besoins, de faire des comp
je laisse comme ça, je trouvais ça plus insistant.

2024-08-06 18:17 UTC, germainlefebvre4 commented on blog/green/20240621-greenIT-introduction-1/index.md
> +*Source : [Systext](https://www.systext.org/sites/all/animationreveal/mtxsmp/#/1) *
```suggestion
*Source : [Systext](https://www.systext.org/sites/all/animationreveal/mtxsmp/#/1)*
```

2024-08-06 18:17 UTC, germainlefebvre4 commented on blog/green/20240621-greenIT-introduction-1/index.md
> +Et oui, avec des composants comme l'Arsenic et l'Antimoine, certes en quantité minime et stabilisé dans votre smartphone, mais qu'en est-il de leur exploitation ?
```suggestion
Et oui, avec des composants comme l'[Arsenic](https://fr.m.wikipedia.org/wiki/Arsenic) et l'[Antimoine](https://fr.m.wikipedia.org/wiki/Antimoine), certes en quantité minime et stabilisé dans votre smartphone, mais qu'en est-il de leur exploitation ?
```

2024-08-06 18:17 UTC, germainlefebvre4 commented on blog/green/20240621-greenIT-introduction-1/index.md
> +Lors du meetup Techrocks du 8 février 2024, j'ai pu apprendre les démarches entreprises, par exemple, par Fairphone qui tente sur le long terme d'améliorer les conditions sociales autour des sites où
```suggestion
Lors du [meetup Techrocks du 8 février 2024](https://youtu.be/pfSUGj5pmag), j'ai pu apprendre les démarches entreprises, par exemple, par Fairphone qui tente sur le long terme d'améliorer les conditions sociales autour des sites où elle source ses matériaux.
```

2024-08-09 10:46 UTC, germainlefebvre4 approved these changes

2024-08-09 21:08 UTC, M3lkior approved these changes

2024-08-09 21:09 UTC, merged