feat(onboarding): joining the company
zatsit-oss/zats-blog-content pull request #21
Opened 2024-07-17 13:50 UTC by jemarray

2024-07-26 09:48 UTC, M3lkior requested changes

2024-07-26 09:48 UTC, M3lkior commented on blog/general/2024-07-16-onboarding/index.md
> +title: Mon onboarding
```suggestion
title: Mon onboarding chez zatsit
```

2024-07-26 09:48 UTC, M3lkior commented on blog/general/2024-07-16-onboarding/index.md
> +Lundi ! Arrivée dans les locaux, je suis accueilli par Flavien et Océane. Un bureau m'attend avec quelques goodies estampillés au couleur de l'entreprise, gourde, sweat, sticker et un petit mot d'acc
```suggestion
Lundi ! Arrivée dans les locaux, je suis accueilli par Flavien (un des co-fondateurs) et Océane (notre chargée de mission RH de choc). Un bureau m'attend avec quelques goodies estampillés au couleur de l'entreprise : gourde, sweat, sticker et un petit mot d'accueil qui me font très plaisir. 
```

2024-07-26 09:48 UTC, M3lkior commented on blog/general/2024-07-16-onboarding/index.md
> +On commence par gérer tout ce que tout le monde « adore »… la partie administrative et tous les divers documents à fournir et quelques validations d’identité habituelles. On active mes accès à [Ekip]
```suggestion
La matinée commence par la partie administrative ( ce que tout le monde « adore », n'est ce pas ? )
- les divers documents à fournir et quelques validations d’identité habituelles. 
- On active mes accès à [Ekip](https://www.ekip.app/). Je découvre ainsi les tickets restaurants **éco-responsables**. 
- Puis avec Océane, on passe en revue les accès aux outils qui permettent le suivi pour mes futures missions. D'ailleurs, **zatsit** a mis en place une plateforme dédiée pour l'onboarding des consultants, permettant mettre en avant les quelques « formations  » à dérouler pour être opérationnel.
```

2024-07-26 09:48 UTC, M3lkior commented on blog/general/2024-07-16-onboarding/index.md
> +
```suggestion
On reparle avec tous le monde de ce l’on veut construire à l’avenir et des impacts que veut avoir **[zatsit](https://zatsit.fr/)** sur les aspects sociétal et environnemental ; Ce qui m’amène à vous parler du choix sur le matériel qu’a fait la société.

```

2024-07-26 09:48 UTC, M3lkior commented on blog/general/2024-07-16-onboarding/index.md
> +## Maintenant le plus cool : mon poste de travail...
```suggestion
## Mon meilleur moment de la journée : la découverte de mon outil de travail
```

2024-07-26 09:48 UTC, M3lkior commented on blog/general/2024-07-16-onboarding/index.md
> +Peu de temps avant mon arrivée, j’ai reçu un message qui me demandait de faire le choix de mon futur poste de travail, ainsi j’ai découvert le concept de [Framework](https://frame.work/fr/fr) ce qui
```suggestion
Peu de temps avant mon arrivée, j’ai reçu un message qui me demandait de choisir la configuration de mon futur poste de travail [Framework](https://frame.work/fr/fr). 
J'ai ainsi découvert leur concept : proposer du matériel réparable et évolutif. Ce choix permet à **zatsit** de rester cohérent dans sa politique environnementale et avoir un impact le plus restreint possible sur la planête. 

J’ai donc choisi les différents éléments de ma machine : un 13 pouces avec coque en aluminium : processeur, ram, disque et extensions… Et pour le fun, le montage à faire par mes soins pour prendre en main l'assemblage du hardware.
```

2024-07-26 09:48 UTC, M3lkior commented on blog/general/2024-07-16-onboarding/index.md
> +Donc tout était là, un carton contenant les diverses parties de mon ordinateur, quand on l’habitude de monter des configurations et comme tout est suffisamment indiqué sur la carte mère, on installe
```suggestion
Donc tout était là, dans un carton contenant les diverses parties de mon ordinateur. Quand on a l’habitude de monter des configurations et comme tout est suffisamment indiqué sur la carte mère, l'assemblage se fait plutôt facilement en en quelques minutes: on installe le disque SSD et la mémoire, on referme avec le couvercle, qui est le clavier, on serre quelque vis avec l’outil fournit, et *zatsit* ! 

Le petit plus sympa : le contour de l’écran est amovible et il existe plusieurs couleurs. Moi, j’ai choisi le orange.
```

2024-07-26 09:48 UTC, M3lkior commented on blog/general/2024-07-16-onboarding/index.md
> +Pour pouvoir alimenter la machine et la connecter à divers équipements extérieurs, il y a 4 emplacements qui peuvent recevoir des modules d’extension en tous genres : USB type A ou C, HDMI, Ethernet
```suggestion
Pour pouvoir alimenter la machine et la connecter à des périphériques, il y a 4 emplacements qui peuvent recevoir des modules d’extension en tous genres : USB type A ou C, HDMI, Ethernet et autres que l'on peut donc interchanger, et à chaud. 

Et pour certaines extensions, on peut également y ajouter un peu de couleur.
```

2024-07-26 09:48 UTC, M3lkior commented on blog/general/2024-07-16-onboarding/index.md
> +Une fois tout en place, j’ai installé une distribution Linux (Ubuntu 24.04) à partir d’une clé USB que j’avais préparé en avance en suivant les indications fournies sur le site du fabriquant. Et tout
indications fournies sur le site du fabriquant -> mettre le lien vers la doc

```suggestion
Une fois tout en place, j’ai installé une distribution Linux (Ubuntu 24.04) à partir d’une clé USB que j’avais préparé en avance en suivant les [indications fournies sur le site du fabriquant](lien ici). 

Tout était fonctionnel au premier démarrage ! 

J’ai commencé à travailler sur ce poste après avoir configuré mon environnent de développement. Je suis déjà enthousiaste à l’idée d'utiliser ma machine au quotidien chez nos clients.
```

2024-07-26 09:48 UTC, M3lkior commented on blog/general/2024-07-16-onboarding/index.md
> +En parcourant le site de Framework [Framework](https://frame.work/fr/fr) on y découvre que beaucoup de matériaux constituant les postes de travail sont en bonne partie recyclé. Qu’il est aussi possib
```suggestion
Parcourir le site de [Framework](https://frame.work/fr/fr) est intéressant : 
- On y découvre que beaucoup de matériaux constituant les postes de travail sont en bonne partie recyclé. 
- Qu’il est aussi possible de commander tous les composants séparément, ce qui permet de réparer ou de faire évoluer sa configuration facilement au fil des années (Idée que je trouve intéressante, quand on a déjà ouvert un ordinateur portable et constaté que l’on ne pourra pas faire grand chose pour le dépanner)
- Chaque composant proposé sur la Markerplace possède sa fiche de réparabilité (dans l'idée) + mettre photo ?
```

2024-07-26 09:48 UTC, M3lkior commented on blog/general/2024-07-16-onboarding/index.md
> +Il reste juste à voir dans le temps comment tout cela va évoluer et peut-être partager mon expérience dans quelques temps sur ce genre de machine.
pas sur que cette ligne est sa place en conclusion d'article :) 

Pourquoi ne pas ajouter un chapitre sur tes semaines en interne avec le déroulé des classroom sur la tech chez nous ?

Par contre je pense qu'il faudrait conclure sur `la suite chez zatsit` non ? comment tu pressent les prochains mois, les sujets internes et externe sur lesquels tu va bosser, la qualité des missions qu'on t'as proposé, etc

2024-07-30 13:10 UTC, jemarray commented on blog/general/2024-07-16-onboarding/index.md
> +title: Mon onboarding
Done

2024-07-30 13:11 UTC, jemarray commented on blog/general/2024-07-16-onboarding/index.md
> +Lundi ! Arrivée dans les locaux, je suis accueilli par Flavien et Océane. Un bureau m'attend avec quelques goodies estampillés au couleur de l'entreprise, gourde, sweat, sticker et un petit mot d'acc
Done

2024-07-30 13:11 UTC, jemarray commented on blog/general/2024-07-16-onboarding/index.md
> +On commence par gérer tout ce que tout le monde « adore »… la partie administrative et tous les divers documents à fournir et quelques validations d’identité habituelles. On active mes accès à [Ekip]
Done

2024-07-30 13:11 UTC, jemarray commented on blog/general/2024-07-16-onboarding/index.md
> +
Done

2024-07-30 13:11 UTC, jemarray commented on blog/general/2024-07-16-onboarding/index.md
> +## Maintenant le plus cool : mon poste de travail...
Done

2024-07-30 13:11 UTC, jemarray commented on blog/general/2024-07-16-onboarding/index.md
> +Donc tout était là, un carton contenant les diverses parties de mon ordinateur, quand on l’habitude de monter des configurations et comme tout est suffisamment indiqué sur la carte mère, on installe
Done

2024-07-30 13:11 UTC, jemarray commented on blog/general/2024-07-16-onboarding/index.md
> +Pour pouvoir alimenter la machine et la connecter à divers équipements extérieurs, il y a 4 emplacements qui peuvent recevoir des modules d’extension en tous genres : USB type A ou C, HDMI, Ethernet
Done

2024-07-30 13:12 UTC, jemarray commented on blog/general/2024-07-16-onboarding/index.md
> +Une fois tout en place, j’ai installé une distribution Linux (Ubuntu 24.04) à partir d’une clé USB que j’avais préparé en avance en suivant les indications fournies sur le site du fabriquant. Et tout
Done

2024-07-30 13:12 UTC, jemarray commented on blog/general/2024-07-16-onboarding/index.md
> +En parcourant le site de Framework [Framework](https://frame.work/fr/fr) on y découvre que beaucoup de matériaux constituant les postes de travail sont en bonne partie recyclé. Qu’il est aussi possib
Done

2024-07-30 13:12 UTC, jemarray commented on blog/general/2024-07-16-onboarding/index.md
> +Il reste juste à voir dans le temps comment tout cela va évoluer et peut-être partager mon expérience dans quelques temps sur ce genre de machine.
Done

2024-07-30 13:19 UTC, jemarray commented on blog/general/2024-07-16-onboarding/index.md
> +Peu de temps avant mon arrivée, j’ai reçu un message qui me demandait de faire le choix de mon futur poste de travail, ainsi j’ai découvert le concept de [Framework](https://frame.work/fr/fr) ce qui
Done

2024-08-02 08:14 UTC, M3lkior requested changes

2024-08-02 08:14 UTC, M3lkior commented on blog/general/2024-07-16-onboarding/index.md
> +Lundi ! Arrivée dans les locaux, je suis accueilli par Flavien (un des co-fondateurs) et Océane (notre chargée de mission RH de choc). Un bureau m'attend avec quelques goodies estampillés au couleur
```suggestion
Lundi ! Arrivée dans les locaux, je suis accueilli par Flavien (un des co-fondateurs) et Océane (notre chargée de mission RH de choc). Un bureau m'attend avec quelques goodies estampillés aux couleurs de l'entreprise : gourde, sweat, sticker et un petit mot d'accueil qui me font très plaisir. 
```

2024-08-02 08:14 UTC, M3lkior commented on blog/general/2024-07-16-onboarding/index.md
> +la matinée commence par la partie administrative (ce que tout le monde « adore », n'est ce pas)
```suggestion
La matinée commence par la partie administrative (ce que tout le monde « adore », n'est ce pas ?)
```

2024-08-02 08:14 UTC, M3lkior commented on blog/general/2024-07-16-onboarding/index.md
> +On reparle avec tous le monde de ce l’on veut construire à l’avenir et des impacts que veut avoir **[zatsit](https://zatsit.fr/)** sur les aspects sociétal et environnemental ; Ce qui m’amène à vous
```suggestion
On reparle avec tous le monde de ce l’on veut construire à l’avenir et des impacts que veut avoir **[zatsit](https://zatsit.fr/)** sur les aspects sociétal et environnemental.

Ce qui m’amène à vous parler du choix sur le matériel qu’a fait la société.
```

2024-08-02 08:14 UTC, M3lkior commented on blog/general/2024-07-16-onboarding/index.md
> +## Mon meilleur moment de la journée : la découverte de mon outil de travail...
```suggestion
## Mon meilleur moment de la journée : la découverte de mon outil de travail
```

2024-08-02 08:14 UTC, M3lkior commented on blog/general/2024-07-16-onboarding/index.md
> +Peu de temps avant mon arrivée, j’ai reçu un message qui me demandait de choisir la configuration de mon futur poste de travail [Framework](https://frame.work/fr/fr)
```suggestion
Peu de temps avant mon arrivée, j’ai reçu un message qui me demandait de choisir la configuration de mon futur poste de travail [Framework](https://frame.work/fr/fr).
```

2024-08-02 08:14 UTC, M3lkior commented on blog/general/2024-07-16-onboarding/index.md
> +Donc tout était là, dans un carton contenant les diverses parties de mon ordinateur. Quand on a l’habitude de monter des configurations et comme tout est suffisamment indiqué sur la carte mère, l'ass
```suggestion
Donc tout était là, dans un carton contenant les diverses parties de mon ordinateur. Quand on a l’habitude de monter des configurations, et comme tout est suffisamment indiqué sur la carte mère, l'assemblage se fait plutôt facilement et en quelques minutes : on installe le disque SSD et la mémoire, on referme avec le couvercle, qui est le clavier, on serre quelque vis avec l’outil qui est fournit, et **zatsit** !
```

2024-08-02 08:14 UTC, M3lkior commented on blog/general/2024-07-16-onboarding/index.md
> +Le petit plus sympa : le contour de l’écran est amovible et il existe plusieurs couleurs, moi j’ai choisi le orange.
```suggestion
Le petit plus sympa : le contour de l’écran est amovible et il existe plusieurs couleurs. Moi, j’ai choisi le orange.
```

2024-08-02 08:14 UTC, M3lkior commented on blog/general/2024-07-16-onboarding/index.md
> +Avant d'avoir une nouvelle affectation chez un client, durant quelques semaines, j'ai commencé les classroom élaborées par des membres de **zatsit**. Les premiers ateliers m’ont permis de découvrir l
```suggestion
En attendant mon démarrage chez un client, j'en ai profité pour commencer les *Classrooms* élaborées par **zatsit**.

Les premiers ateliers m’ont permis de découvrir les principes de l’éco-conception ou d’étudier et de comprendre les solutions de monitoring pour l’empreinte carbone de projets cloud. 

La société veut sensibiliser ses collaborateurs aux impacts environnementaux de nos métiers. 
```

2024-08-02 08:14 UTC, M3lkior commented on blog/general/2024-07-16-onboarding/index.md
> +Des sujets très intéressants et que j’avais un peu survoler jusqu’à aujourd’hui. Cela va impacter ma façon de concevoir mes futurs projets en tant que développeur. Ces classroom permettent aussi les
```suggestion
Des sujets très intéressants et que j’avais un peu survolé jusqu’à aujourd’hui. Cela va **impacter** ma façon de concevoir mes futurs projets en tant que technical leader.
```

2024-08-02 08:14 UTC, M3lkior commented on blog/general/2024-07-16-onboarding/index.md
> +## Mon avenir chez zatsit...
```suggestion
## Mon avenir chez zatsit ?
```

2024-08-02 08:14 UTC, M3lkior commented on blog/general/2024-07-16-onboarding/index.md
> +Je pense que les mois à venir vont être enrichissants et vont encore me faire grandir.
```suggestion
Je suis persuadé que les mois à venir vont être enrichissants et vont me faire grandir.
```

2024-08-02 08:14 UTC, M3lkior commented on blog/general/2024-07-16-onboarding/index.md
> +D’une part, l’équipe **zatsit** est à l’écoute de mes souhaits sur le périmètre de mes futures missions et de mes envies de découvrir d’autres écosystèmes chez nos clients, de me donner l’opportunité
```suggestion
D’une part, l’équipe **zatsit** est à l’écoute quant à mes souhaits sur le périmètre de mes futures missions, mes envies de découvrir d’autres écosystèmes chez nos clients, et de me donner l’opportunité de faire mes preuves en tant que tech lead.
```

2024-08-02 08:14 UTC, M3lkior commented on blog/general/2024-07-16-onboarding/index.md
> +Pour donner un exemple, on se prépare à participer à l’Hacktoberfest, événement qui encourage les développeurs à contribuer à des projets open source.
```suggestion

Pour donner un exemple, on se prépare à participer à l’Hacktoberfest, événement qui encourage les développeurs à contribuer sur des projets open source.
```

2024-08-02 08:14 UTC, M3lkior commented on blog/general/2024-07-16-onboarding/index.md
> +Et il se peut que l’on se croise lors d’un BBL ou d’un Meetup sur des sujets passionnants organisé par **zatsit**
```suggestion
Il se peut d'ailleurs que l’on se croise lors d’un BBL, ou d’un Meetup sur des sujets passionnants organisé par **zatsit**

Alors, prêt à rejoindre l'aventure **zatsit** ?
```

2024-08-02 13:54 UTC, M3lkior approved these changes, later dismissed

2024-08-02 15:46 UTC, emmanuelperu reviewed
Il faut remplacer les images ou des numéros de series (même difficilement visibles au zoom) apparaissent en les floutant ou en apposant le logo zatsit.

2024-08-02 15:46 UTC, emmanuelperu commented on blog/general/2024-07-16-onboarding/index.md
> +Mon arrivée dans une nouvelle aventure !
```suggestion
Mon arrivée dans une nouvelle aventure ! Découvrez les valeurs que j'aime chez **zatsit** et comment se passe l'onboarding.
```

2024-08-02 15:46 UTC, emmanuelperu commented on blog/general/2024-07-16-onboarding/index.md
> +Lundi ! Arrivée dans les locaux, je suis accueilli par Flavien (un des co-fondateurs) et Océane (notre chargée de mission RH de choc). Un bureau m'attend avec quelques goodies estampillés aux couleur
```suggestion
Lundi ! Arrivée dans les locaux, je suis accueilli par Flavien (un des co-fondateurs) et Océane (notre chargée de missions RH de choc). Un bureau m'attend avec quelques goodies estampillés aux couleurs de l'entreprise : gourde en métal recyclé, sweat (dont le fabricant et membre de fairwear.org), sticker et un petit mot d'accueil qui me font très plaisir. 
```

2024-08-02 15:46 UTC, emmanuelperu commented on blog/general/2024-07-16-onboarding/index.md
> +Une fois tout en place, j’ai installé une distribution Linux (Ubuntu 24.04) à partir d’une clé USB que j’avais préparé en avance en suivant les [indications fournies sur le site du fabriquant](https:
```suggestion
Une fois tout en place, j’ai installé une distribution Linux (Ubuntu 24.04) à partir d’une clé USB 
 en suivant les [indications fournies sur le site du fabriquant](https://guides.frame.work/Guide/Ubuntu+22.04+LTS+Installation+on+the+Framework+Laptop+13/109).
```

2024-08-02 15:46 UTC, emmanuelperu commented on blog/general/2024-07-16-onboarding/index.md
> +Une fois tout en place, j’ai installé une distribution Linux (Ubuntu 24.04) à partir d’une clé USB que j’avais préparé en avance en suivant les [indications fournies sur le site du fabriquant](https:
Elle s'est perdue dans le déménagement, mais on la fournit normalement, je vais en refaire une.

2024-08-02 15:46 UTC, emmanuelperu commented on blog/general/2024-07-16-onboarding/index.md
> +- on y découvre que beaucoup de matériaux constituant les postes de travail sont en bonne partie recyclé.
```suggestion
- On y découvre que beaucoup de matériaux constituant les postes de travail sont en bonne partie recyclés.
```

2024-08-02 15:46 UTC, emmanuelperu commented on blog/general/2024-07-16-onboarding/index.md
> +## En attendant de trouver la mission de mes rêves...
```suggestion
## En attendant de démarrer mon nouveau projet client...
```

2024-08-02 15:46 UTC, emmanuelperu commented on blog/general/2024-07-16-onboarding/index.md
> +D’autres part, je vais pouvoir prendre part à des projets en interne toujours en lien avec les convictions de la société qui vont favoriser les échanges au sein d’un collectif de passionnés.
```suggestion
D’autre part, je vais pouvoir participer à des projets internes toujours en lien avec les convictions de la société qui vont favoriser les échanges au sein d’un collectif de passionnés.
```

2024-08-02 15:46 UTC, emmanuelperu commented on blog/general/2024-07-16-onboarding/index.md
> +
```suggestion

J'ai pu collaborer à un premier projet, qui m'a fait découvrir certaines solutions de Firebase et Google Cloud Platform, auquel mes collègues pourront contribuer dans les semaines qui arrivent.
```

2024-08-05 08:01 UTC, jemarray commented on blog/general/2024-07-16-onboarding/index.md
> +Une fois tout en place, j’ai installé une distribution Linux (Ubuntu 24.04) à partir d’une clé USB que j’avais préparé en avance en suivant les [indications fournies sur le site du fabriquant](https:
Elle est bien sur le bureau mais je voulais le faire from scratch

2024-08-06 22:14 UTC, germainlefebvre4 commented on blog/general/2024-07-16-onboarding/index.md
> +On reparle avec tous le monde de ce l’on veut construire à l’avenir et des impacts que veut avoir **[zatsit](https://zatsit.fr/)** sur les aspects sociétal et environnemental.
```suggestion
On reparle avec tout le monde de ce l’on veut construire à l’avenir et des impacts que veut avoir **[zatsit](https://zatsit.fr/)** sur les aspects sociétal et environnemental.
```

2024-08-06 22:14 UTC, germainlefebvre4 commented on blog/general/2024-07-16-onboarding/index.md
> +Donc tout était là, dans un carton contenant les diverses parties de mon ordinateur. Quand on a l’habitude de monter des configurations, et comme tout est suffisamment indiqué sur la carte mère, l'as
```suggestion
Donc tout était là, dans un carton contenant les diverses parties de mon ordinateur. Quand on a l’habitude de monter des configurations, et comme tout est suffisamment indiqué sur la carte mère, l'assemblage se fait plutôt facilement et en quelques minutes : on installe le disque SSD et la mémoire, on referme avec le couvercle, qui est le clavier, on serre quelque vis avec l’outil qui est fourni, et **zatsit** !
```

2024-08-06 22:14 UTC, germainlefebvre4 commented on blog/general/2024-07-16-onboarding/index.md
> +- Qu’il est aussi possible de commander tous les composants séparément (cela va jusqu'au kit de visserie) ce qui permet de réparer ou de faire évoluer sa configuration facilement au fil des années (I
```suggestion
- Qu’il est aussi possible de commander tous les composants séparément (cela va jusqu'au kit de visserie) ce qui permet de réparer ou de faire évoluer sa configuration facilement au fil des années (idée que je trouve intéressante quand on à déjà ouvert un ordinateur portable et constaté que l’on ne pourra pas faire grand chose pour la remettre sur pieds)
```

2024-08-06 22:14 UTC, germainlefebvre4 commented on blog/general/2024-07-16-onboarding/index.md
> +- Pour chaque composant proposé sur la marketplace, il existe un tutoriel de remplacement avec la difficulté, les étapes et le temps nécessaire à l'opération. Ce qui permet d'effectuer facilement la
```suggestion
- Pour chaque composant proposé sur la marketplace, il existe un tutoriel de remplacement avec le niveau de difficulté, les étapes et le temps nécessaire à l'opération. Ce qui permet d'effectuer facilement la maintenance de son poste de travail par ses propres moyens.
```

2024-08-06 22:14 UTC, germainlefebvre4 commented on blog/general/2024-07-16-onboarding/index.md
> +J'ai pu collaborer à un premier projet, qui m'a fait découvrir certaines solutions de Firebase et Google Cloud Platform, auquel mes collègues pourront contribuer dans les semaines qui arrivent.
```suggestion
J'ai pu collaborer sur un premier projet, qui m'a fait découvrir certaines solutions de Firebase et Google Cloud Platform, auquel mes collègues pourront contribuer dans les semaines qui arrivent.
```

2024-08-09 09:08 UTC, emmanuelperu approved these changes

2024-08-09 09:09 UTC, emmanuelperu approved these changes, later dismissed

2024-08-09 10:45 UTC, germainlefebvre4 submitted a review, later dismissed

2024-08-09 16:26 UTC, jemarray commented
@emmanuelperu 
J'ai effacé les données sur les images que j'ai prises, mais pas sur celle provenant du site.

2024-08-09 21:11 UTC, M3lkior approved these changes

2024-08-30 14:16 UTC, emmanuelperu approved these changes

2024-08-30 14:17 UTC, merged