feat(cloud): Crossplane
zatsit-oss/zats-blog-content pull request #27
Opened 2024-10-25 14:06 UTC by germainlefebvre4

2024-11-15 11:03 UTC, emmanuelperu reviewed
Il

2024-11-15 11:03 UTC, emmanuelperu commented on blog/cloud/2024-10-25-crossplane/index.md
> +Crossplane est une extension open-source à Kubernete qui permet aux équipes plateforme d'assembler l'infrastructure provenant de plusieurs cloud providers, et d'exposer des APIs de plus haut niveau p
```suggestion
Crossplane est une extension open-source à Kubernetes qui permet aux équipes plateforme d'assembler l'infrastructure provenant de plusieurs cloud providers, et d'exposer des APIs de plus haut niveau pour que les équipes d'applicatives puissent les consommer.
```

2024-11-15 11:03 UTC, emmanuelperu commented on blog/cloud/2024-10-25-crossplane/index.md
> +Crossplane se définit comme annoncé sur leur baseline...
```suggestion
Crossplane se définit comme annoncé sur leur baseline :
```

2024-11-15 11:03 UTC, emmanuelperu commented on blog/cloud/2024-10-25-crossplane/index.md
> +...comme un orchestrateur de ressources multi-cloud.
A ok, j'avais pas compris les ... je ne peux pas visualier la page, là faut voir ce que ça donne

2024-11-15 11:03 UTC, emmanuelperu commented on blog/cloud/2024-10-25-crossplane/index.md
> +## Introduction
Bizarre qu'il y ait quelque chose avant l'introduction.

2024-11-15 11:03 UTC, emmanuelperu commented on blog/cloud/2024-10-25-crossplane/index.md
> +Membre de la CNCF depuis 2020, ils ont rejoint le programme d'incubation (incubating) en 2021, ce qui en fait un projet prometteur.
```suggestion
Membre de la CNCF depuis 2020, ils ont rejoint le programme d'incubation (incubating) en 2021, dans la catégorie "Scheduling & Orchestration" ce qui en fait un projet prometteur, puisque synonyme de stabilité et d'utilisation en production.
```

2024-11-15 11:03 UTC, emmanuelperu commented on blog/cloud/2024-10-25-crossplane/index.md
> +Membre du programme *Incubation* de la CNCF depuis 2021, Crossplane est considéré comme un projet sérieux, prometteur et ambitieux par les SIG/TOC de la CNCF.
Le paragraphe existe déjà, erreur de copier/coller ?

2024-11-15 11:03 UTC, emmanuelperu commented on blog/cloud/2024-10-25-crossplane/index.md
> +Crossplane est un projet open-source, disponible sur [GitHub](https://github.com/crossplane/crossplane) sous licence Apache 2.0 et majoritairement développé par la société [Upbound](https://upbound.i
```suggestion
Crossplane est un projet open source, disponible sur [GitHub](https://github.com/crossplane/crossplane) sous licence Apache 2.0 et majoritairement développé par la société [Upbound](https://upbound.io/).
```

2024-11-15 11:03 UTC, emmanuelperu commented on blog/cloud/2024-10-25-crossplane/index.md
> +Crossplane se démarque de ses concurrents par sa capacité à gérer des ressources et appliquer les modifications en temps réel. Le pattern de réconciliation lui permet d'être réactif et d'appliquer le
2 fois temps réel, peut-être a reformuler ou un synonyme (en live)

2024-11-15 11:03 UTC, emmanuelperu commented on blog/cloud/2024-10-25-crossplane/index.md
> +Chaque Provider s'installe avec des CRDs spécifiques qui définissent les ressources gérées par le Provider. Ces CRDs permettent de décrire l'objet distant à créer, mettre à jour ou supprimer.
peut-être mettre un lien sur CRD pour aller vers https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/

2024-11-15 11:03 UTC, emmanuelperu commented on blog/cloud/2024-10-25-crossplane/index.md
> +Pour les Providers complexes, on retoruve le découpage par ressource sous la forme de Provider Family.
```suggestion
Pour les Providers complexes, on retrouve le découpage par ressource sous la forme de Provider Family.
```

2024-11-15 11:03 UTC, emmanuelperu commented on blog/cloud/2024-10-25-crossplane/index.md
> +* `claim` et `spec` : qui définit la dénomination et la structure du Claim sous forme d'une CRD
```suggestion
* `claim` et `spec` : qui définissent la dénomination et la structure du Claim sous forme d'une CRD
```

2024-11-15 11:03 UTC, emmanuelperu commented on blog/cloud/2024-10-25-crossplane/index.md
> +La XRD définit à la fois la XRC et la XR afin de garantir une cohérence entre les deux objets manipulés. La XR n'a de sens que si les valeurs manipulées sont bien définit par les paramètres utilisate
```suggestion
La XRD définit à la fois la XRC et la XR afin de garantir une cohérence entre les deux objets manipulés. La XR n'a de sens que si les valeurs manipulées sont bien définies par les paramètres utilisateur.
```

2024-11-15 11:03 UTC, emmanuelperu commented on blog/cloud/2024-10-25-crossplane/index.md
> +Par exemple, pour notre Composition `JobNotif`, l'utilisateur final n'a pas besoin de connaître les sous-ressources créées en dessous, telle que le Service Account (SA) et ses credentials, la gestion
```suggestion
Par exemple, pour notre Composition `JobNotif`, l'utilisateur final n'a pas besoin de connaître les sous-ressources créées en dessous, telle que le Service Account (SA) et ses credentials, la gestion des policies liées au SA ainsi que le stockage des valeurs sensibles dans le Secret Manager. Toute cette complexité doit être masquée pour ne fournir à l'utilisateur la seule véritable information utile : le nom du Topic.
```

2024-11-15 21:23 UTC, germainlefebvre4 commented on blog/cloud/2024-10-25-crossplane/index.md
> +## Introduction
Effectivement, je dois nettoyer cette partie

2024-11-19 17:08 UTC, germainlefebvre4 commented
Il me manque encore la section XR à écrire

2024-11-29 14:46 UTC, emmanuelperu approved these changes, later dismissed

2024-12-02 20:47 UTC, M3lkior requested changes
peux tu transformer tes png en webp ? avif  si pas trop long ?
il faudrait également changer la date pour que l'article apparaissent apres celui du hacktobert ? tu peux ajouter une metadata dans le header pour surcharger la date de publication

2024-12-11 06:46 UTC, germainlefebvre4 commented
> peux tu transformer tes png en webp ? avif si pas trop long ? il faudrait également changer la date pour que l'article apparaissent apres celui du hacktobert ? tu peux ajouter une metadata dans le header pour surcharger la date de publication

@M3lkior:

* Images converties en webp
* Date mise à jour

2024-12-12 19:51 UTC, M3lkior approved these changes

2024-12-12 19:52 UTC, M3lkior commented
on publie quand tu veux @germainlefebvre4  :)

2024-12-13 12:22 UTC, merged