feat(architecture): add article on realworld app
zatsit-oss/zats-blog-content pull request #28
Opened 2024-10-29 07:04 UTC by Mcfloy

2024-10-29 20:26 UTC, M3lkior requested changes

2024-10-29 20:26 UTC, M3lkior commented on blog/architecture/2024-10-29-Realworld-app/index.md
> +authors: [lperreau]
ajoute toi en auteur via authors/authors.yml via le format 

```

slorber:
  name: Sébastien Lorber
  title: Docusaurus maintainer
  url: https://sebastienlorber.com
  image_url: https://github.com/slorber.png
  socials:
    x: sebastienlorber
    github: slorber
```

2024-10-31 08:54 UTC, Mcfloy commented on blog/architecture/2024-10-29-Realworld-app/index.md
> +authors: [lperreau]
C'est ajouté 👍

2024-11-08 10:25 UTC, M3lkior requested changes

2024-11-08 10:25 UTC, M3lkior commented on blog/architecture/2024-10-29-Realworld-app/index.md
> +title: "Realworld ou la mère des applications démo"
```suggestion
title: "Realworld, ou la mère des applications démo"
```

2024-11-08 10:25 UTC, M3lkior commented on blog/architecture/2024-10-29-Realworld-app/index.md
> +`Hello, world!` Et voilà ! Je sais comment développer avec `[insérer language ou framework du moment]` ! 🤓
[insérer language ou framework du moment] ne devrait pas etre remplacé ? :p 
Si pas, j'aurais plus mis une tournure du genre 
```suggestion
`Hello, world!` Et voilà ! Je sais comment développer avec `Vue | Java | Rust | GoLang` ! 🤓
```

2024-11-08 10:25 UTC, M3lkior commented on blog/architecture/2024-10-29-Realworld-app/index.md
> +Comment ça, ce n'est pas suffisant ? Si seulement il y avait un exemple d'application qui couvre tous les aspects d'une application moderne...
je pense qu'il faudrait orienter cette phrase genre
```suggestion
Faire de la veille sur un project technologique nécessite de trouver des use-cases d'implémentation, ce qui n'est jamais vraiment simple a trouver, non ? 
```

2024-11-08 10:25 UTC, M3lkior commented on blog/architecture/2024-10-29-Realworld-app/index.md
> +Oh mais attendez, j'ai entendu parler de _Realworld_ !
```suggestion
Ca tombe bien, on a la solution pour vous : _Realworld_ !
```

2024-11-08 10:25 UTC, M3lkior commented on blog/architecture/2024-10-29-Realworld-app/index.md
> +Alors n'hésitez pas à chercher votre bonheur là-dedans, et si vous ne trouvez pas, pourquoi ne pas contribuer en [ajoutant votre propre implémentation](https://codebase.show/projects/realworld/implem
il faudrait transformer cette phrase en paragraphe de conclusion 

il manque également le footer de partage de l'article dans le markdown non ?

2024-11-08 13:08 UTC, Mcfloy commented on blog/architecture/2024-10-29-Realworld-app/index.md
> +`Hello, world!` Et voilà ! Je sais comment développer avec `[insérer language ou framework du moment]` ! 🤓
Oui c'était plus une blague mais ok pour le remplacer 🤔

2024-11-15 16:53 UTC, emmanuelperu approved these changes, later dismissed

2024-11-15 16:53 UTC, emmanuelperu commented on authors/authors.yml
> +lperreau:
Il y a une nouvelle feature sur le dev pour partager si tu le souhaites des liens vers les réseaux sociaux.

2024-12-02 20:49 UTC, M3lkior approved these changes

2024-12-02 20:50 UTC, merged