Feat/general 20241028 tyranny of convenience
zatsit-oss/zats-blog-content pull request #29
Opened 2024-10-29 21:16 UTC by sergejomon

2024-11-15 10:31 UTC, emmanuelperu commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +
Il manque la ligne <!-- truncate --> pour pouvoir avoir le résumé en page liste.

2024-11-15 10:31 UTC, emmanuelperu commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +Traduction directe de l'Anglais "tyranny of convenience", le concept n'est pas si récent. Evan Williams, co-fondateur de Twitter, le déclarait déjà en 2018 : « la commodité décide de tout ».
```suggestion
Traduction litérale de l'Anglais "tyranny of convenience", le concept n'est pas si récent. Evan Williams, co-fondateur de Twitter, le déclarait déjà en 2018 : « la commodité décide de tout ».
```

2024-11-15 10:31 UTC, emmanuelperu commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +Nous savons que le fast-food est mauvais pour la santé, qu'il y a plein d'alternatives au moins aussi savoureuses et meilleures pour la santé,
```suggestion
Nous savons que le fast-food est mauvais pour la santé, qu'il y a plein d'alternatives souvent plus savoureuses et meilleures pour la santé,
```

2024-11-15 10:31 UTC, emmanuelperu commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +mais parce que sortir de la commodité nous semble impossible, impensable. C'est le moment où la commodité n'est plus un plus mais une contrainte.
```suggestion
mais parce que sortir de la commodité nous semble impossible, impensable. C'est le moment où la commodité n'est plus un atout, mais une contrainte.
```

2024-11-15 10:31 UTC, emmanuelperu commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +L'IT est particulièrement sensible à cette problématique. Tenu par des objectifs d'efficacité et de rapidité, il est facile d'aller au plus simple et surtout, d'y rester.
```suggestion
Le monde du numérique est particulièrement sensible à cette problématique. Tenu par des objectifs d'efficacité et de rapidité, il est facile d'aller au plus simple et surtout, d'y rester. 
```

2024-11-15 10:31 UTC, emmanuelperu commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +
N'est-il pas commode de devenir esclave de la commodité ?

2024-11-15 10:31 UTC, emmanuelperu commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +passer de l'un à l'autre quand une nouvelle fonctionnalité fait son apparition cjez la concurrence.
```suggestion
passer de l'un à l'autre quand une nouvelle fonctionnalité fait son apparition chez la concurrence.
```

2024-11-15 10:31 UTC, emmanuelperu commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +Plus Amazon devient accessible, plus les gens l'utilisent, et ce cycle renforce la portée et l'attrait d'Amazon, en faisant le choix privilégié et par défaut
```suggestion
Plus Amazon devient accessible, plus les gens l'utilisent, et ce cycle renforce la portée et l'attrait d'Amazon, en faisant le choix privilégié et par défaut.
```

2024-11-15 10:31 UTC, emmanuelperu commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +Et encore plus dans nos métiers : aucun·e professionel·le de l'IT ne travaillerait sur Windows sans y être contraint par... la tyrannie de la commodité.
```suggestion
Et encore plus dans nos métiers : aucun·e professionel·le du numérique ne travaillerait sur Windows sans y être contraint par... la tyrannie de la commodité. 
```

2024-11-15 10:31 UTC, emmanuelperu commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +Et encore plus dans nos métiers : aucun·e professionel·le de l'IT ne travaillerait sur Windows sans y être contraint par... la tyrannie de la commodité.
On a des exemples, même chez zatsit ou certains de nos collègues choisissent volontairement Windows, vu que nos matériels arrivent sans OS, c'est donc un choix. C'est peut être too much. Par contre, est-ce qu'ils aiment vraiment ou par commodité de compatibilité avec des jeux, des softs habituels... bonne question ;-)

2024-11-15 10:31 UTC, emmanuelperu commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +On a l'habitude de cet environnement, on a grandi avec. Pire ! On y est parfois contraint par les protocoles de sécurités de notre entreprise ou de nos clients, car les VPNs, les antivirus, fournit p
```suggestion
On a l'habitude de cet environnement, on a grandi avec. Pire ! On y est parfois contraint par les protocoles de sécurités de notre entreprise ou de nos clients, car les VPNs, les antivirus, fournis par des sociétés tierces, ne supportent pas d'autres OS. Ou pour plus cher.
```

2024-11-15 10:31 UTC, emmanuelperu commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +À Zatsit, nous avons eu par exemple l'occasion dans le cadre de nos journées de recherche en greenIT de tester Scaphandre, un outil de monitoring de la consommation énergétique des clusters kubernete
```suggestion
Chez **zatsit**, nous avons eu par exemple l'occasion, dans le cadre de nos journées de recherche en greenIT, de tester Scaphandre, un outil de monitoring de la consommation énergétique des clusters kubernetes. 
```

2024-11-15 10:31 UTC, emmanuelperu commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +Open source, un tel outil permettrait d'avoir des mesures directes de consommation réelle. Problème : les fournisseurs cloud comme Google ou Amazon n'exposent pas ces metrics.
```suggestion
Open source, un tel outil permettrait d'avoir des mesures directes de consommation réelle. Problème : les fournisseurs cloud comme Google ou Amazon n'exposent pas ces metriques.
```

2024-11-15 10:31 UTC, emmanuelperu commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +Bloquée dans son utilisation, mais aussi son développement : difficile de mobiliser la communauté FOSS autour d'un outil qui est inutilisable dans 90% des cas de production.
```suggestion
Bloquée dans son utilisation, mais aussi son développement : difficile de mobiliser la communauté FOSS autour d'un outil qui est inutilisable dans énormément de cas de production.
```

2024-11-15 10:31 UTC, emmanuelperu commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +Nous vous proposons 3 axes, faciles à mettre en place dans votre quotidien et dans son environnement professionnel pour lutter contre la tyrannie de la commodité :
```suggestion
Nous vous proposons 3 axes, faciles à mettre en place dans votre quotidien et dans son environnement professionnel, pour lutter contre la tyrannie de la commodité :
```

2024-11-15 10:31 UTC, emmanuelperu commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +parce que c'est ce qui est fait partout ailleurs dans le projet, parce que votre cloud provider propose une solution clef en main, parce que c'est inclu dans notre offre, parce que c'est un outil que
```suggestion
parce que c'est ce qui est fait partout ailleurs dans le projet, parce que votre cloud provider propose une solution clef en main, parce que c'est inclus dans notre offre, parce que c'est un outil que vous maitrisez déjà...)
```

2024-11-15 10:31 UTC, emmanuelperu commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +Prenez le temps d'envisager d'autres options, de regarder du côté de l'open source. Ne partez pas du principe que le plus évident et le plus rationnel.
```suggestion
Prenez le temps d'envisager d'autres options, de regarder du côté de l'open source. Ne partez pas du principe que le plus évident est le plus rationnel.
```

2024-11-15 10:31 UTC, emmanuelperu commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +Comme nous l'avons vu, la tyrannie de la commodité a des effets plus larges qu'à l'échelle d'un projet, d'un choix technique, ou de l'achat nouveau smartphone : elle appauvrit tout notre environnemen
```suggestion
Comme nous l'avons vu, la tyrannie de la commodité a des effets plus larges qu'à l'échelle d'un projet, d'un choix technique, ou de l'achat d'un nouveau smartphone : elle appauvrit tout notre environnement technique,
```

2024-11-15 10:31 UTC, emmanuelperu commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +
Il faudrait peut-être une conclusion avec une autre citation sur la commodité et nuancer un petit peu. À la lecture de ton article, j'ai (très subjectif) l'impression que TOUS nos choix sont par commodités. Dernière suggestion : on pourrait appuyer ton argumentaire sur le marketing par les noms de produits qui sont devenus des noms commun ou des verbes, alors qu'ils ne sont pas forcément les meilleurs produits. Scotch, ou Post-it (car on ne veut pas dire petite feuille de papier autoadhésive amovible), On prend un Uber parceque l'appli est simple et rapide, mais finalement appeler un chauffeur de taxi qui a du métier n'est-il pas mieux pour l'ipact économique local, la qualité du transport... ou autre exemple.

2024-11-15 10:31 UTC, emmanuelperu commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +### La commodité et son influence sur l'innovation
Il faudrait peut être aérer ce paragraphe et trouver une illustration ou une autre citation

2024-11-15 10:31 UTC, emmanuelperu commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +Mais cette centralisation a un effet délétère : le monopole fait littéralement disparaître la concurrence. Ainsi, de nombreux produits ne sont plus disponibles ailleurs que sur Amazon.
Tu utilises beaucoup Mais, il faut peut être alterner avec cependant, en revanche...

2024-11-18 10:37 UTC, sergejomon commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +Et encore plus dans nos métiers : aucun·e professionel·le de l'IT ne travaillerait sur Windows sans y être contraint par... la tyrannie de la commodité.
Moi je pense que c'est pas commodité, notament pour les dev dotnet qui sont dépendant de tout ce que fais VS pour eux (alors qu'on peut faire du dotnet proprement avec un IDE jetbrain). Mais n'importe qui qui a déjà du redémarrer son windows pour appliquer le changement de path de la version de java/node sait que windows c'est pas pratique pour faire de l'informatique

2024-11-18 12:44 UTC, sergejomon commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +Mais cette centralisation a un effet délétère : le monopole fait littéralement disparaître la concurrence. Ainsi, de nombreux produits ne sont plus disponibles ailleurs que sur Amazon.
Done

2024-11-29 15:37 UTC, sergejomon commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +Nous savons que le fast-food est mauvais pour la santé, qu'il y a plein d'alternatives au moins aussi savoureuses et meilleures pour la santé,
done

2024-11-29 15:37 UTC, sergejomon commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +L'IT est particulièrement sensible à cette problématique. Tenu par des objectifs d'efficacité et de rapidité, il est facile d'aller au plus simple et surtout, d'y rester.
done

2024-11-29 15:37 UTC, sergejomon commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +Prenez le temps d'envisager d'autres options, de regarder du côté de l'open source. Ne partez pas du principe que le plus évident et le plus rationnel.
done

2024-11-29 15:37 UTC, sergejomon commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +Et encore plus dans nos métiers : aucun·e professionel·le de l'IT ne travaillerait sur Windows sans y être contraint par... la tyrannie de la commodité.
done

2024-11-29 15:37 UTC, sergejomon commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +À Zatsit, nous avons eu par exemple l'occasion dans le cadre de nos journées de recherche en greenIT de tester Scaphandre, un outil de monitoring de la consommation énergétique des clusters kubernete
done

2024-11-29 15:38 UTC, sergejomon commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +Bloquée dans son utilisation, mais aussi son développement : difficile de mobiliser la communauté FOSS autour d'un outil qui est inutilisable dans 90% des cas de production.
done

2024-11-29 15:54 UTC, emmanuelperu requested changes

2024-11-29 15:54 UTC, emmanuelperu commented on blog/craftmanship/2024-10-25-tyranny-of-convenience/index.md
> +Mais nous savons aussi que tout est affaire de compromis et que l'on ne peut pas ignorer les contraintes de temps et de moyen. Il ne faut pas tomber dans une position extrême où tout ce qui est effic
```suggestion
Mais nous savons aussi que tout est affaire de compromis et que l'on ne peut pas ignorer les contraintes de temps et de moyen. 

Il ne faut pas tomber dans une position extrême où tout ce qui est efficace et pratique deviendrait suspect !
```

2025-02-15 19:08 UTC, merged